name: Main CI

on:
  release:
    types:
      - published

jobs:

  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy To Vercel Production
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./packages/app

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

      # Checkout The Repo Locally
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Setup Env
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install

      # Build React App
      - name: Build React App
        run: yarn workspace app build

      # Preview Directory
      - run: ls
      - run: ls packages/app/build


